In [16]:
import pandas as pd

df = pd.read_csv('/home/hojin/text2sql-agent/mlflow_experiments/text2sql_eval/eval/results_v2.csv')

In [17]:
df

,id,difficulty,category,user_query,generated_sql,valid_sql,exec_success,exec_accuracy,error_msg,latency_ms
0,tc_001,easy,단순조회,삼성전자 2023년 영업이익 알려줘,"SELECT c.corp_name, f.bsns_year, f.amount\nFRO...",True,False,False,NaN,4283
1,tc_002,easy,단순조회,SK하이닉스 2022년 당기순이익 알려줘,"SELECT c.corp_name, f.bsns_year, f.amount\nFRO...",True,False,False,NaN,1705
2,tc_003,easy,단순조회,현대자동차 2023년 매출액 알려줘,"SELECT c.corp_name, f.bsns_year, f.amount\nFRO...",True,False,False,NaN,2044
3,tc_004,easy,단순조회,LG전자 2023년 자산총계 알려줘,"SELECT c.corp_name, f.bsns_year, f.amount\nFRO...",True,False,False,NaN,1459
4,tc_005,easy,단순조회,카카오 2022년 부채총계 알려줘,"SELECT c.corp_name, f.bsns_year, f.amount\nFRO...",True,False,False,NaN,1404
5,tc_006,easy,단순조회,POSCO홀딩스 2023년 자본총계 알려줘,"SELECT c.corp_name, f.bsns_year, f.amount\nFRO...",True,False,False,NaN,5409
6,tc_007,easy,단순조회,셀트리온 2023년 현금및현금성자산 알려줘,"SELECT c.corp_name, f.bsns_year, f.amount\nFRO...",True,False,False,NaN,1280
7,tc_008,easy,단순조회,KB금융 2023년 법인세비용 알려줘,"SELECT c.corp_name, f.bsns_year, f.amount\nFRO...",True,False,True,NaN,6829
8,tc_009,medium,기간비교,삼성전자 2020~2023년 영업이익 추이 알려줘,"SELECT f.bsns_year, f.amount\nFROM financial_f...",True,False,True,NaN,963
9,tc_010,medium,기간비교,현대자동차 최근 3년 매출액 추이 알려줘,"SELECT f.bsns_year, f.amount\nFROM financial_f...",True,False,True,NaN,7000
10,tc_011,medium,기간비교,LG화학 2021~2023년 당기순이익 변화 알려줘,"SELECT f.bsns_year, f.amount\nFROM financial_f...",True,False,True,NaN,1473
11,tc_012,medium,기간비교,SK하이닉스 2020~2023년 자산총계 추이 알려줘,"SELECT f.bsns_year, f.amount\nFROM financial_f...",True,False,True,NaN,3063
12,tc_013,medium,기간비교,NAVER 최근 4년 영업비용 추이 알려줘,"SELECT f.bsns_year, f.amount\nFROM financial_f...",True,False,True,NaN,5038
13,tc_014,medium,기간비교,기아 2021~2023년 유동부채 추이 알려줘,"SELECT f.bsns_year, f.amount\nFROM financial_f...",True,False,True,NaN,9463
14,tc_015,medium,기간비교,삼성바이오로직스 2020~2023년 무형자산 추이 알려줘,"SELECT f.bsns_year, f.amount\nFROM financial_f...",True,False,True,NaN,2617
15,tc_016,medium,기간비교,신한지주 2021~2023년 법인세비용 추이 알려줘,"SELECT f.bsns_year, f.amount\nFROM financial_f...",True,False,True,NaN,6894
16,tc_017,medium,파생지표,삼성전자 2023년 영업이익률 알려줘,"SELECT \n c.corp_name, \n f.bsns_year, \...",True,False,True,NaN,9614
17,tc_018,medium,파생지표,현대자동차 2023년 부채비율 알려줘,"SELECT \n c.corp_name, \n f.bsns_year, \...",True,False,True,NaN,9258
18,tc_019,medium,파생지표,LG전자 2023년 유동비율 알려줘,"SELECT c.corp_name, f.bsns_year, \n MAX(...",True,False,True,NaN,-921
19,tc_020,medium,파생지표,카카오 2022년 ROE 알려줘,"SELECT c.corp_name, f.bsns_year, \n ROUN...",True,False,True,"(psycopg2.errors.GroupingError) column ""c.corp...",5761
20,tc_021,medium,파생지표,SK하이닉스 2023년 매출총이익률 알려줘,"SELECT \n c.corp_name, \n f.bsns_year, \...",True,False,True,NaN,7512
21,tc_022,medium,파생지표,POSCO홀딩스 2022년 자기자본비율 알려줘,"SELECT c.corp_name, f.bsns_year, \n MAX(...",True,False,True,NaN,8736
22,tc_023,hard,기업간비교,삼성전자와 SK하이닉스 2023년 영업이익 비교해줘,"SELECT c.corp_name, f.bsns_year, f.amount\nFRO...",True,False,True,NaN,5862
23,tc_024,hard,기업간비교,현대자동차와 기아 2022~2023년 매출액 비교해줘,"SELECT \n c.corp_name, \n f.bsns_year, \...",True,False,True,NaN,3792
24,tc_025,hard,기업간비교,삼성전자와 LG전자 2023년 부채비율 비교해줘,"SELECT \n c.corp_name, \n ROUND(MAX(CASE...",True,False,True,NaN,7826
25,tc_026,hard,기업간비교,KB금융과 신한지주 2023년 자산총계 비교해줘,"SELECT c.corp_name, f.amount\nFROM financial_f...",True,False,True,NaN,4861
26,tc_027,hard,기업간비교,셀트리온과 삼성바이오로직스 2023년 무형자산 비교해줘,"SELECT c.corp_name, f.bsns_year, f.amount\nFRO...",True,False,True,NaN,2532
27,tc_028,hard,복합조건,2023년 영업이익 상위 5개사 알려줘,"SELECT c.corp_name, f.amount\nFROM financial_f...",True,True,True,NaN,4458
28,tc_029,hard,복합조건,2023년 부채비율이 가장 낮은 기업 알려줘,"SELECT c.corp_name, f.amount\nFROM financial_f...",True,False,True,NaN,2533
29,tc_030,hard,복합조건,2022~2023년 영업이익 증가율이 가장 높은 기업 알려줘,"WITH increase_rate AS (\n SELECT c.corp_name,...",False,False,True,Invalid SQL,1813

In [18]:
## error가 뜬것만 체크
df_is_error = df.loc[df['error_msg'].notna()]
df_is_error

,id,difficulty,category,user_query,generated_sql,valid_sql,exec_success,exec_accuracy,error_msg,latency_ms
19,tc_020,medium,파생지표,카카오 2022년 ROE 알려줘,"SELECT c.corp_name, f.bsns_year, \n ROUN...",True,False,True,"(psycopg2.errors.GroupingError) column ""c.corp...",5761
29,tc_030,hard,복합조건,2022~2023년 영업이익 증가율이 가장 높은 기업 알려줘,"WITH increase_rate AS (\n SELECT c.corp_name,...",False,False,True,Invalid SQL,1813

In [20]:
df = df.iloc[[0]] # 0번째 행을 데이터프레임 형식으로 가져옴

# 이제 df는 DataFrame이므로 아래 코드가 작동함
print(df[['generated_sql']].to_string())

                                                                                                                                                                                                            generated_sql
0  SELECT c.corp_name, f.bsns_year, f.amount\nFROM financial_fact f\nJOIN company_dim c ON f.corp_code = c.corp_code\nWHERE c.corp_name = '삼성전자'\nAND f.account_nm = '영업이익'\nAND f.bsns_year = 2023\nAND f.fs_div = 'CFS'